PERMISSION_GROUPS = [
    {"name": "Users", "slug": "users", "description": "User management permissions", "sort_order": 1},
    {"name": "Products", "slug": "products", "description": "Product management permissions", "sort_order": 2},
    {"name": "Orders", "slug": "orders", "description": "Order management permissions", "sort_order": 3},
    {"name": "Payments", "slug": "payments", "description": "Payment and transaction permissions", "sort_order": 4},
    {"name": "Wallet", "slug": "wallet", "description": "Wallet management permissions", "sort_order": 5},
    {"name": "Escrow", "slug": "escrow", "description": "Escrow management permissions", "sort_order": 6},
    {"name": "Reviews", "slug": "reviews", "description": "Review management permissions", "sort_order": 7},
    {"name": "Messages", "slug": "messages", "description": "Messaging permissions", "sort_order": 8},
    {"name": "Notifications", "slug": "notifications", "description": "Notification permissions", "sort_order": 9},
    {"name": "Categories", "slug": "categories", "description": "Category management permissions", "sort_order": 10},
    {"name": "Roles & Permissions", "slug": "roles", "description": "Authorization system permissions", "sort_order": 11},
    {"name": "Reports", "slug": "reports", "description": "Report and analytics permissions", "sort_order": 12},
    {"name": "Settings", "slug": "settings", "description": "Platform settings permissions", "sort_order": 13},
    {"name": "Support", "slug": "support", "description": "Support ticket permissions", "sort_order": 14},
    {"name": "Disputes", "slug": "disputes", "description": "Dispute resolution permissions", "sort_order": 15},
    {"name": "Affiliates", "slug": "affiliates", "description": "Affiliate program permissions", "sort_order": 16},
]

DEFAULT_PERMISSIONS = [
    {"resource": "users", "action": "create", "name": "Create Users", "group": "users"},
    {"resource": "users", "action": "view", "name": "View Users", "group": "users"},
    {"resource": "users", "action": "update", "name": "Update Users", "group": "users"},
    {"resource": "users", "action": "delete", "name": "Delete Users", "group": "users"},
    {"resource": "users", "action": "ban", "name": "Ban Users", "group": "users"},
    {"resource": "users", "action": "suspend", "name": "Suspend Users", "group": "users"},
    {"resource": "users", "action": "verify", "name": "Verify Users", "group": "users"},
    {"resource": "users", "action": "export", "name": "Export Users", "group": "users"},
    {"resource": "products", "action": "create", "name": "Create Products", "group": "products"},
    {"resource": "products", "action": "view", "name": "View Products", "group": "products"},
    {"resource": "products", "action": "update", "name": "Update Products", "group": "products"},
    {"resource": "products", "action": "delete", "name": "Delete Products", "group": "products"},
    {"resource": "products", "action": "approve", "name": "Approve Products", "group": "products"},
    {"resource": "products", "action": "reject", "name": "Reject Products", "group": "products"},
    {"resource": "products", "action": "feature", "name": "Feature Products", "group": "products"},
    {"resource": "products", "action": "publish", "name": "Publish Products", "group": "products"},
    {"resource": "products", "action": "archive", "name": "Archive Products", "group": "products"},
    {"resource": "orders", "action": "create", "name": "Create Orders", "group": "orders"},
    {"resource": "orders", "action": "view", "name": "View Orders", "group": "orders"},
    {"resource": "orders", "action": "update", "name": "Update Orders", "group": "orders"},
    {"resource": "orders", "action": "cancel", "name": "Cancel Orders", "group": "orders"},
    {"resource": "orders", "action": "refund", "name": "Refund Orders", "group": "orders"},
    {"resource": "orders", "action": "delete", "name": "Delete Orders", "group": "orders"},
    {"resource": "orders", "action": "export", "name": "Export Orders", "group": "orders"},
    {"resource": "payments", "action": "view", "name": "View Payments", "group": "payments"},
    {"resource": "payments", "action": "process", "name": "Process Payments", "group": "payments"},
    {"resource": "payments", "action": "refund", "name": "Refund Payments", "group": "payments"},
    {"resource": "payments", "action": "void", "name": "Void Payments", "group": "payments"},
    {"resource": "payments", "action": "export", "name": "Export Transactions", "group": "payments"},
    {"resource": "wallet", "action": "view", "name": "View Wallet", "group": "wallet"},
    {"resource": "wallet", "action": "deposit", "name": "Deposit to Wallet", "group": "wallet"},
    {"resource": "wallet", "action": "withdraw", "name": "Withdraw from Wallet", "group": "wallet"},
    {"resource": "wallet", "action": "adjust", "name": "Adjust Wallet Balance", "group": "wallet"},
    {"resource": "wallet", "action": "freeze", "name": "Freeze Wallet", "group": "wallet"},
    {"resource": "escrow", "action": "view", "name": "View Escrow", "group": "escrow"},
    {"resource": "escrow", "action": "release", "name": "Release Escrow", "group": "escrow"},
    {"resource": "escrow", "action": "hold", "name": "Hold Escrow", "group": "escrow"},
    {"resource": "escrow", "action": "reverse", "name": "Reverse Escrow", "group": "escrow"},
    {"resource": "reviews", "action": "create", "name": "Create Reviews", "group": "reviews"},
    {"resource": "reviews", "action": "view", "name": "View Reviews", "group": "reviews"},
    {"resource": "reviews", "action": "update", "name": "Update Reviews", "group": "reviews"},
    {"resource": "reviews", "action": "delete", "name": "Delete Reviews", "group": "reviews"},
    {"resource": "reviews", "action": "moderate", "name": "Moderate Reviews", "group": "reviews"},
    {"resource": "messages", "action": "send", "name": "Send Messages", "group": "messages"},
    {"resource": "messages", "action": "read", "name": "Read Messages", "group": "messages"},
    {"resource": "messages", "action": "delete", "name": "Delete Messages", "group": "messages"},
    {"resource": "messages", "action": "moderate", "name": "Moderate Messages", "group": "messages"},
    {"resource": "notifications", "action": "send", "name": "Send Notifications", "group": "notifications"},
    {"resource": "notifications", "action": "read", "name": "Read Notifications", "group": "notifications"},
    {"resource": "notifications", "action": "manage", "name": "Manage Notification Templates", "group": "notifications"},
    {"resource": "categories", "action": "create", "name": "Create Categories", "group": "categories"},
    {"resource": "categories", "action": "view", "name": "View Categories", "group": "categories"},
    {"resource": "categories", "action": "update", "name": "Update Categories", "group": "categories"},
    {"resource": "categories", "action": "delete", "name": "Delete Categories", "group": "categories"},
    {"resource": "roles", "action": "create", "name": "Create Roles", "group": "roles"},
    {"resource": "roles", "action": "view", "name": "View Roles & Permissions", "group": "roles"},
    {"resource": "roles", "action": "update", "name": "Update Roles", "group": "roles"},
    {"resource": "roles", "action": "delete", "name": "Delete Roles", "group": "roles"},
    {"resource": "roles", "action": "assign", "name": "Assign Roles to Users", "group": "roles"},
    {"resource": "roles", "action": "manage_permissions", "name": "Manage Role Permissions", "group": "roles"},
    {"resource": "permissions", "action": "create", "name": "Create Permissions", "group": "roles"},
    {"resource": "permissions", "action": "view", "name": "View Permissions", "group": "roles"},
    {"resource": "permissions", "action": "update", "name": "Update Permissions", "group": "roles"},
    {"resource": "permissions", "action": "delete", "name": "Delete Permissions", "group": "roles"},
    {"resource": "permissions", "action": "direct_assign", "name": "Assign Direct Permissions", "group": "roles"},
    {"resource": "feature_flags", "action": "create", "name": "Create Feature Flags", "group": "roles"},
    {"resource": "feature_flags", "action": "view", "name": "View Feature Flags", "group": "roles"},
    {"resource": "feature_flags", "action": "update", "name": "Update Feature Flags", "group": "roles"},
    {"resource": "feature_flags", "action": "delete", "name": "Delete Feature Flags", "group": "roles"},
    {"resource": "reports", "action": "view", "name": "View Reports", "group": "reports"},
    {"resource": "reports", "action": "generate", "name": "Generate Reports", "group": "reports"},
    {"resource": "reports", "action": "export", "name": "Export Reports", "group": "reports"},
    {"resource": "analytics", "action": "view", "name": "View Analytics", "group": "reports"},
    {"resource": "analytics", "action": "export", "name": "Export Analytics", "group": "reports"},
    {"resource": "settings", "action": "view", "name": "View Settings", "group": "settings"},
    {"resource": "settings", "action": "update", "name": "Update Settings", "group": "settings"},
    {"resource": "settings", "action": "manage", "name": "Manage Platform Settings", "group": "settings"},
    {"resource": "support", "action": "create", "name": "Create Support Tickets", "group": "support"},
    {"resource": "support", "action": "view", "name": "View Support Tickets", "group": "support"},
    {"resource": "support", "action": "update", "name": "Update Support Tickets", "group": "support"},
    {"resource": "support", "action": "assign", "name": "Assign Support Tickets", "group": "support"},
    {"resource": "support", "action": "close", "name": "Close Support Tickets", "group": "support"},
    {"resource": "disputes", "action": "create", "name": "Create Disputes", "group": "disputes"},
    {"resource": "disputes", "action": "view", "name": "View Disputes", "group": "disputes"},
    {"resource": "disputes", "action": "update", "name": "Update Disputes", "group": "disputes"},
    {"resource": "disputes", "action": "resolve", "name": "Resolve Disputes", "group": "disputes"},
    {"resource": "disputes", "action": "escalate", "name": "Escalate Disputes", "group": "disputes"},
    {"resource": "disputes", "action": "evidence", "name": "Manage Dispute Evidence", "group": "disputes"},
    {"resource": "affiliates", "action": "view", "name": "View Affiliates", "group": "affiliates"},
    {"resource": "affiliates", "action": "manage", "name": "Manage Affiliates", "group": "affiliates"},
    {"resource": "affiliates", "action": "commission", "name": "Manage Commission Rates", "group": "affiliates"},
    {"resource": "audit_logs", "action": "view", "name": "View Audit Logs", "group": "roles"},
    {"resource": "authorization_logs", "action": "view", "name": "View Authorization Logs", "group": "roles"},
]

DEFAULT_ROLES = [
    {
        "name": "Guest", "slug": "guest", "description": "Unauthenticated visitor",
        "priority": 0, "is_default": False,
        "permissions": [
            "products:view", "categories:view", "reviews:view",
        ],
    },
    {
        "name": "Buyer", "slug": "buyer", "description": "Registered buyer",
        "priority": 10, "is_default": True,
        "permissions": [
            "products:view", "products:create", "categories:view", "reviews:view",
            "reviews:create", "orders:create", "orders:view", "orders:cancel",
            "wallet:view", "wallet:deposit", "messages:send", "messages:read",
            "notifications:read", "support:create", "support:view",
            "disputes:create", "disputes:view", "disputes:evidence",
        ],
    },
    {
        "name": "Seller", "slug": "seller", "description": "Registered seller",
        "priority": 20, "is_default": False,
        "permissions": [
            "products:view", "products:create", "products:update", "products:delete",
            "products:publish", "products:archive", "categories:view",
            "reviews:view", "orders:view", "orders:update",
            "wallet:view", "wallet:deposit", "wallet:withdraw",
            "messages:send", "messages:read", "notifications:read",
            "support:create", "support:view", "disputes:view",
        ],
    },
    {
        "name": "Verified Seller", "slug": "verified_seller", "description": "Verified seller with elevated trust",
        "priority": 25, "is_default": False,
        "permissions": [
            "products:view", "products:create", "products:update", "products:delete",
            "products:publish", "products:archive", "products:feature",
            "categories:view", "reviews:view",
            "orders:view", "orders:update",
            "wallet:view", "wallet:deposit", "wallet:withdraw",
            "messages:send", "messages:read", "notifications:read",
            "support:create", "support:view", "disputes:view",
        ],
    },
    {
        "name": "Moderator", "slug": "moderator", "description": "Content moderator",
        "priority": 40, "is_default": False,
        "permissions": [
            "products:view", "products:approve", "products:reject", "products:update",
            "products:delete", "products:feature", "categories:create",
            "categories:update", "categories:delete", "categories:view",
            "reviews:view", "reviews:moderate", "reviews:delete",
            "orders:view", "messages:read", "messages:moderate",
            "disputes:view", "disputes:update", "disputes:evidence",
            "notifications:send",
        ],
    },
    {
        "name": "Support Agent", "slug": "support_agent", "description": "Customer support agent",
        "priority": 30, "is_default": False,
        "permissions": [
            "users:view", "orders:view", "orders:update",
            "support:view", "support:update", "support:assign", "support:close",
            "disputes:view", "disputes:update", "disputes:evidence",
            "messages:read", "messages:send", "notifications:send",
            "reviews:view",
        ],
    },
    {
        "name": "Finance Manager", "slug": "finance_manager", "description": "Finance and payment operations",
        "priority": 50, "is_default": False,
        "permissions": [
            "orders:view", "orders:refund", "orders:export",
            "payments:view", "payments:process", "payments:refund", "payments:void", "payments:export",
            "wallet:view", "wallet:adjust", "wallet:freeze",
            "escrow:view", "escrow:release", "escrow:hold", "escrow:reverse",
            "users:view", "reports:view", "reports:generate", "reports:export",
            "analytics:view", "analytics:export",
        ],
    },
    {
        "name": "Content Manager", "slug": "content_manager", "description": "Content and category management",
        "priority": 35, "is_default": False,
        "permissions": [
            "products:view", "products:approve", "products:reject", "products:update",
            "products:delete", "products:feature",
            "categories:create", "categories:view", "categories:update", "categories:delete",
            "reviews:view", "reviews:moderate", "reviews:delete",
            "notifications:send",
        ],
    },
    {
        "name": "Administrator", "slug": "admin", "description": "Platform administrator",
        "priority": 90, "is_default": False,
        "permissions": [
            "users:create", "users:view", "users:update", "users:delete",
            "users:ban", "users:suspend", "users:verify", "users:export",
            "products:view", "products:create", "products:update", "products:delete",
            "products:approve", "products:reject", "products:feature",
            "products:publish", "products:archive",
            "orders:view", "orders:update", "orders:cancel", "orders:refund", "orders:delete", "orders:export",
            "payments:view", "payments:process", "payments:refund", "payments:void", "payments:export",
            "wallet:view", "wallet:adjust", "wallet:freeze",
            "escrow:view", "escrow:release", "escrow:hold", "escrow:reverse",
            "reviews:view", "reviews:moderate", "reviews:delete",
            "messages:read", "messages:moderate", "messages:delete",
            "notifications:send", "notifications:manage",
            "categories:create", "categories:view", "categories:update", "categories:delete",
            "roles:create", "roles:view", "roles:update", "roles:delete",
            "roles:assign", "roles:manage_permissions",
            "permissions:create", "permissions:view", "permissions:update", "permissions:delete",
            "permissions:direct_assign",
            "feature_flags:create", "feature_flags:view", "feature_flags:update", "feature_flags:delete",
            "reports:view", "reports:generate", "reports:export",
            "analytics:view", "analytics:export",
            "settings:view", "settings:update",
            "support:view", "support:update", "support:assign", "support:close",
            "disputes:view", "disputes:update", "disputes:resolve", "disputes:escalate", "disputes:evidence",
            "affiliates:view", "affiliates:manage", "affiliates:commission",
            "audit_logs:view", "authorization_logs:view",
        ],
    },
    {
        "name": "Super Administrator", "slug": "super_admin", "description": "Super administrator with all permissions",
        "priority": 100, "is_default": False,
        "permissions": [f"{r}:{a}" for r in [
            "users", "products", "orders", "payments", "wallet", "escrow",
            "reviews", "messages", "notifications", "categories", "roles",
            "permissions", "feature_flags", "reports", "analytics", "settings",
            "support", "disputes", "affiliates", "audit_logs", "authorization_logs",
        ] for a in [
            "create", "view", "update", "delete", "manage", "assign",
            "approve", "reject", "feature", "publish", "archive",
            "ban", "suspend", "verify", "export",
            "cancel", "refund", "process", "void",
            "deposit", "withdraw", "adjust", "freeze",
            "release", "hold", "reverse",
            "moderate", "send", "read",
            "generate", "resolve", "escalate", "evidence",
            "close", "commission", "direct_assign", "manage_permissions",
        ]],
    },
]
